### ISSUE TITLE
Unable to install in Windows

### ISSUE THREAD

**Issue by rtb21** [timpalpant/mprofile#1]
When installing mprofile in Windows the following error is generated:

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\bacon\AppData\Local\Temp\pip-install-sx88i9tf\mprofile\setup.py", line 29, in <module>
        pythonapi = ctypes.cdll.LoadLibrary(None)
      File "C:\Program Files\Python37\lib\ctypes\__init__.py", line 442, in LoadLibrary
        return self._dlltype(name)
      File "C:\Program Files\Python37\lib\ctypes\__init__.py", line 364, in __init__
        self._handle = _dlopen(self._name, mode)
    TypeError: LoadLibrary() argument 1 must be str, not None
```

Thanks!

**Comment by timpalpant** [comment]
Sadly mprofile only supports UNIX systems (Linux, BSD, macOS) right now. I do not have the resources to port it to Windows, but would be happy to merge changes if someone else is able to do so.
